### ISSUE TITLE
Update IJ1 dependency version

### ISSUE THREAD

**Issue by frauzufall** [scijava/pom-scijava#126]
related:
- https://github.com/imagej/ij1-patcher/pull/47

**Comment by imagejan** [comment]
When https://github.com/imagej/ij1-patcher/pull/47 is merged, we are ready to pin to ij version 1.53b.

**Comment by ctrueden** [comment]
I did not want to include this as part of the pom-scijava 29 work—it will further delay the release—but I agree it's important. So I'll try to review and merge and the great work @imagejan has done as soon as I can. It's going to take a little time because we need to ensure that ij1-patcher/imagej-legacy works with _all released versions of ij1_, not just the latest one.

**Comment by imagejan** [comment]
@ctrueden wrote:
> we need to ensure that ij1-patcher/imagej-legacy works with all released versions of ij1, not just the latest one.

I had this in mind when working on https://github.com/imagej/ij1-patcher/pull/47, but due to the `Button` fields initialized in `GenericDialog` between 1.52t and 1.53a, I didn't find a way to make `ij1-patcher` build with these versions. So those versions will probably work fine with a normal Fiji installation, but might have problems with running headless.
Regardless, version 1.53b and *all versions before* 1.52s should work fine.

While I agree with the goal of providing a maximum of compatibility between versions, I would *really, really* like to see ij.jar 1.53b in a default Fiji installation very soon, because it contains several fixes that are important for me now: the `https.proxyHost` setting, and the fast TIFF writing to network drives on Windows.

**Comment by ctrueden** [comment]
I hear you @imagejan. I just cut the release of ij1-patcher 1.1.0, which assuming the Travis build succeeds, I'll update in pom-scijava very shortly.

**Comment by ctrueden** [comment]
ij1-patcher updated in d7795baee39a809617f49dd752e8ca8469f2aa69
