### ISSUE TITLE
Bio-Formats 5.3.0

### ISSUE THREAD

**Issue by sbesson** [scijava/pom-scijava#26]
Hi @ctrueden and everyone,

following the release of [Bio-Formats 5.3.0](http://lists.openmicroscopy.org.uk/pipermail/ome-users/2016-December/006284.html), a few questions related to the propagation to the scijava stack and its impact. This release includes a rearchitecture of the low-level components which are now decoupled and versioned independently. In addition 2 components have been renamed:
- `formats-common` is now `ome-common`
- `mdbtools-java` is now `ome-mdbtools`

Before opening a PR to bump the version numbers, I wanted to see how you want to handle this for consumers the base Scijava POM. For instance, should the `formats-common.version` be pinned to the latest version and/or removed completely in favor of `ome-common.version`? Any other impact you can think of?

**Comment by ctrueden** [comment]
I would favor removing the version properties for obsolete components in favor of the new names, and bumping the major version digit of pom-scijava, since we use SemVer in this context to document breaking changes in downstream builds. Leaving the build properties in place would probably result in builds which get "stuck" at old artifact versions without even realizing it.
