### ISSUE TITLE
Version stored in .module doesn't match pom version for use with Gradle

### ISSUE THREAD

**Issue by petebankhead** [scijava/pom-scijava#281]
Very possible this is an issue of me not understanding, but I'm unable to access the version catalog in Gradle with the error
```
Could not resolve all artifacts for configuration 'incomingCatalogForSciJava0'.
> Could not find pom-scijava-19.0.0.toml (org.scijava:pom-scijava:39.0.0).
  Searched in the following locations:
      https://repo.maven.apache.org/maven2/org/scijava/pom-scijava/39.0.0/pom-scijava-19.0.0.toml
```

Checking [pom-scijava-38.0.1.module](https://repo.maven.apache.org/maven2/org/scijava/pom-scijava/38.0.1/pom-scijava-38.0.1.module) I see
```
{
  "formatVersion": "1.1",
  "component": {
    "group": "org.scijava",
    "module": "pom-scijava",
    "version": "19.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
```
which seems to be the version of `pom-scijava-base` (19.0.0) and *not* of `pom-scijava` (38.0.1).

Since the logic for setting the version in `build.gradle.kts` is
```kotlin
version = File("../pom.xml").readText().substringAfter("<version>").substringBefore('<')
```
is this an error that occurs because of the order in which versions appear in the xml?

(The bigger picture: I'm having problems using `scijava-pom` for dependencies with native libraries, because it uses profile activation based on `os.family` and [it seems Gradle doesn't support that](https://discuss.gradle.org/t/how-to-download-transitive-dependency/43506/2) - so I was hoping that a switch to use the version catalog here might help me figure out a workaround)

Thanks!

**Comment by ctrueden** [comment]
@petebankhead Thanks a lot for trying out the Gradle catalog! Much appreciated. :+1: 

I guess you are the first person to try using it in practice, because this is clearly a major error. I think your diagnosis of the issue is correct. It's too late now to fix the 38.0.1 or 39.0.0 pom-scijava releases, but [I fixed the logic](8d52f8be32807079626ec78240d26d71ecf4367c). I will release version 40.0.0 ASAP, but in the course of testing this I found that I had neglected to reenable pom-scijava's integration tests for the past few weeks, so now they need to run (which can take hours), and then I need to fix any newly uncovered problems, before I can release 40.0.0. I'll keep you posted.

**Comment by ctrueden** [comment]
The issue with native library dependencies is something @elect86 was previously thinking about how best to address. Related issues and repositories: #241, [os-maven-plugin](https://github.com/trustin/os-maven-plugin), [native-lib-loader](https://github.com/scijava/native-lib-loader), scijava/native-lib-loader#50.

**Comment by ctrueden** [comment]
I've [released pom-scijava 40.0.0 to OSS Sonatype](https://s01.oss.sonatype.org/#nexus-search;gav~org.scijava~pom-scijava~40.0.0~~); should be mirrored to Maven Central within the next few minutes.

**Comment by petebankhead** [comment]
It works, thanks! After importing the version catalog as `sciJava`, I can now work around the profile problem with

```kotlin
dependencies {
    implementation(sciJava.bundles.fiji)
    {
        exclude(group = "org.jogamp.gluegen")
        exclude(group = "org.jogamp.jogl")
        exclude(group = "org.jogamp.joal")
        exclude(group = "org.bytedeco", module = "ffmpeg")
    }
    implementation(sciJava.org.jogamp.gluegen.gluegenRt)
    implementation(sciJava.org.jogamp.jogl.joglAll)
    implementation(sciJava.org.bytedeco.ffmpeg)
    // Can apply the JavaCPP Gradle plugin to avoid getting dependencies for all platforms here
    implementation("org.bytedeco:ffmpeg-platform:${sciJava.org.bytedeco.ffmpeg.get().version}")

    val classifier = getJogampClassifier()
    if (classifier != null) {
        implementation("org.jogamp.gluegen:gluegen-rt:${sciJava.org.jogamp.gluegen.gluegenRt.get().version}:natives-macosx-universal")
        implementation("org.jogamp.jogl:jogl-all:${sciJava.org.jogamp.jogl.joglAll.get().version}:natives-macosx-universal")
        implementation("org.jogamp.joal:joal:${sciJava.org.jogamp.joal.joal.get().version}:natives-macosx-universal")
    } else {
        logger.warn("Native libraries not found for jogamp")
    }
}


fun getJogampClassifier(): String? {
    if (Os.isFamily(Os.FAMILY_MAC)) {
        return "natives-macosx-universal"
    }
    if (Os.isFamily(Os.FAMILY_WINDOWS)) {
        return "natives-windows-amd64"
    }
    if (Os.isFamily(Os.FAMILY_UNIX)) {
        return if (Os.isArch("arm64")) {
            "natives-linux-aarch64"
        } else {
            "natives-linux-amd64"
        }
    }
    return null
}
```

**Comment by ctrueden** [comment]
@petebankhead Awesome!

One question: I see these lines amongst the above:
```kotlin
implementation("org.jogamp.gluegen:gluegen-rt:${sciJava.org.jogamp.gluegen.gluegenRt.get().version}:natives-macosx-universal")
implementation("org.jogamp.jogl:jogl-all:${sciJava.org.jogamp.jogl.joglAll.get().version}:natives-macosx-universal")
implementation("org.jogamp.joal:joal:${sciJava.org.jogamp.joal.joal.get().version}:natives-macosx-universal")
```
This is hardcoding for macOS... it should instead be:
```
implementation("org.jogamp.gluegen:gluegen-rt:${sciJava.org.jogamp.gluegen.gluegenRt.get().version}:$classifier")
implementation("org.jogamp.jogl:jogl-all:${sciJava.org.jogamp.jogl.joglAll.get().version}:$classifier")
implementation("org.jogamp.joal:joal:${sciJava.org.jogamp.joal.joal.get().version}:$classifier")
```
Right?

**Comment by petebankhead** [comment]
Oops, it should indeed, you can see what I was developing with....

**Comment by elect86** [comment]
I'd like to do some prototyping starting from a native library

Which one do you think would be the best, @ctrueden ?

**Comment by ctrueden** [comment]
@elect86 Sorry for the slow reply. I'm afraid I don't fully understand your question. Are you looking for a Java library in the SciJava component collection that depends on a JAR-wrapped native library using these native classifiers? If so, one high-level example is Fiji itself: https://github.com/fiji/fiji/blob/c82b94e540838b90071bc8dd67dac58f9c7b1fff/pom.xml#L861-L870

It seems to me that we could simply export all these version properties also to the Gradle catalog as variables, no? Or is that not how catalogs work?

**Comment by elect86** [comment]
I just finished a prototype to re-publish the jogl libraries as variants

![Image](https://github.com/user-attachments/assets/7ac29e2c-7fbb-41b8-b99c-4399574aefdf)

I'd like to use your case, @petebankhead, to test it out.. would you be available for that?

The idea is to have a Gradle plugin automatically setting the OS and Arch attributes based on the running system and then having Gradle fetching the right variant by itself

So that you'd just have to write

```
        implementation(sciJava.org.jogamp.gluegen.gluegenRt)
        implementation(scijava.org.jogamp.jogl.joglAll)
        implementation(scijava.org.jogamp.joal.joal)
```

**Comment by elect86** [comment]
Maven classifiers are actually used

What I'm trying to do is writing some logic for the consumer that will automatically bind and add the corresponding native for the running system underneath at the `runtime` configuration ([example](https://docs.gradle.org/6.0-rc-3/userguide/component_metadata_rules.html#adding_variants_for_native_jars))

**Comment by ctrueden** [comment]
OK, so if I understand correctly, the syntax will be something like:
```gradle
dependencies {
    components {
        withModule<JoglRule>("org.jogamp.jogl:jogl-all")
    }
    implementation("org.jogamp.jogl:jogl-all:2.5.0")
}
```
?

Rather than republishing the JOGL artifacts, could this `JoglRule` simply be part of SciJava's Gradle logic?

**Comment by elect86** [comment]
That `Rule` example serve as a showcase how to solve the issue at a consumer level. Unfortunately the same problem will appear as soon as it will publish itself

So, this is a non-solution for us

What we need, is to fix properly the Gradle metadata in order to support the native library dependency properly by loading the right one in the runtime configuration. This will also maintain consticency

I wrote a [plugin](https://github.com/GradleUp/variant-republisher/tree/master) that programmatically can re-publish a given project encoding the native libraries as variant to be properly selected at runtime

I tested it locally and it works fine (both hello-triangle sample and publishing on its turn), we can give it a try on the scijava maven, if you agree, starting with jogamp with the following GAVs

```
    implementation("org.scijava:gluegen-rt:2.5.0")
    implementation("org.scijava:jogl-all:2.5.0")
```
