### ISSUE TITLE
Current Version of ImgLib2-algorithm in Fiji uses outdated ImgLib2 and crashes

### ISSUE THREAD

**Issue by StephanPreibisch** [scijava/pom-scijava#50]
Hi,

in the current Fiji (pom-scijava 16.1.0) we use imglib2-algorithms 0.8.0 which is compiled against imglib2-3.2.0 instead of the new imglib2-4.2.1 which comes with Fiji. This does crash if for example Gauss3 wants to instantiate a new CellImg as temporary image.

This hardly happens for most users I guess but is quite a problem for us. What would be the easiest way to fix this? I can do it on our update site, but this is a bigger problem I think.

Thanks a lot,
Stephan

**Comment by imagejan** [comment]
I'd say this is rather a problem of `pom-imglib2` 9.0.0 as it overrides the version properties here:

https://github.com/imglib/pom-imglib2/blob/pom-imglib2-9.0.0/pom.xml#L113-L123

Is there a version of `imglib2-algorithm` that is actually built against imglib2-4.2.1 and could be uploaded to the Java-8 update site as a quick fix?

**Comment by ctrueden** [comment]
@tpietzsch How would you like to proceed?

**Comment by axtimwalde** [comment]
@StephanPreibisch @ctrueden how dos "crash" manifest?  May be you can easily fix it?  I just checked out both repos and there is no compile nor test error in imglib2-algorithm-0.8.2-SNAPSHOT when I build it.

**Comment by ctrueden** [comment]
I agree that an MCVE would be helpful here. @StephanPreibisch could you please post a very short script which illustrates the issue when executed from an up-to-date Fiji's Script Editor?

**Comment by StephanPreibisch** [comment]
It crashes when instantiating a CellImg here, for that the input needs to be larger than 2^32 pixels in size:
https://github.com/imglib/imglib2-algorithm/blob/33e53d9e66418be261ebb13da35410c28d84db0a/src/main/java/net/imglib2/algorithm/gauss3/SeparableSymmetricConvolution.java#L441

**Comment by StephanPreibisch** [comment]
Here is the example Beanshell script that crashes it:

`import net.imglib2.type.numeric.integer.UnsignedByteType;
import net.imglib2.view.Views;
import net.imglib2.algorithm.gauss3.Gauss3;
import net.imglib2.img.Img;
import net.imglib2.img.cell.CellImgFactory;
import ij.IJ;

IJ.log( "instantiating cellimg" );
Img img = new CellImgFactory().create( new long[]{ 1700, 1700, 1700 }, new UnsignedByteType() );
IJ.log( "running gauss" );
Gauss3.gauss( new double[]{ 1, 1, 1 }, Views.extendZero( img ), img );
`

**Comment by StephanPreibisch** [comment]
The reason is that the constructor of the CellImg changed from Imglib2-3.2.0 to 4.2.1. I will also soon modify Gauss3 since it should allow the specification of the ImgFactory and not just use ArrayImg or CellImg.

**Comment by axtimwalde** [comment]
@StephanPreibisch I don't get this.  If this is a bug that isn't already fixed, it should manifest as a compile error.  But there is no compile error when I change the imglib2 dependency to 4.3.0 in imglib2-algorithm.  Does that mean that we simply need a release of imglib2-algorithm master in Fiji?

**Comment by StephanPreibisch** [comment]
Hi, exactly ... there is no bug in the code, just in the dependencies. The problem is that the current release is shipped with imglib2-algorithm that was built against imglib2-3.2.0, but at the same time it actually comes with imglib-4.2.1. Hence it crashes when trying to find the old CellImg constructor. 

In more details, the current pom-scijava 16.1.0 defines the following versions:
- imglib2-4.2.1
- imglib2-algorithms-0.8.0 >>> which, however says it needs imglib2-3.2.0 that it was built with

Is it clear?

I could easily fix it in the imglib2-poms, but since I cannot do any releases that do not make Travis say that the built failed I cannot do it - different story, see here (https://github.com/fiji/SPIM_Registration/issues/129#issuecomment-320009298).

**Comment by axtimwalde** [comment]
@StephanPreibisch ok.  That wasn't clear to me before.  Have you tried imglib2-algorithm-0.8.1?

**Comment by ctrueden** [comment]
I agree with @StephanPreibisch that this is a bug in pom-scijava version 16.1.0, which is currently the latest release:

* That BOM specifies imglib2-algorithm version 0.8.0.
* That version of imglib2-algorithm invokes `CellImgFactory(int)` which does not exist in imglib2 version 4.x.
* But the BOM specifies imglib2 version 4.2.1.

Commit ef9ee51ee08301da07b91d9d4c445ee7cb3ef24d updates the BOM to imglib2-algorithm 0.8.1, but that is not sufficient, because that release—and indeed imglib2-algorithm's current master branch—still uses that old no-longer-existent constructor of `CellImgFactory(int)`.

The reason the compiler does not fail when updating imglib2-algorithm to depend on imglib2 4.x is because there _is_ a constructor `CellImgFactory(int...)` which is now selected there (appropriately) instead.

So I guess the fix is indeed to update imglib2-algorithm to depend on imglib2 4.x, and release a new imglib2-algorithm 0.8.2. However, as pointed out by @imagejan, the current pom-imglib2 still specifies imglib2 3.3.0. Therefore, the ball is the court of the ImgLib2 maintainers to either: A) update pom-imglib2 and release a version 10.0.0, then update imglib2-algorithm to depend on it; or B) override `imglib2.version` in `imglib2-algorithm` to depend on the new imglib2. Once one of those two things is done, we can cut imglib2-algorithm 0.8.2 and update the pom-scijava BOM accordingly.

**Comment by ctrueden** [comment]
@StephanPreibisch wrote:
> I think I just don't really get something about how to do releases with Travis ...

Sorry for my slowness in investigating that issue. I am extremely backlogged right now. We are also still exploring the best way forward for how to cut releases of all these components without relying on the ImageJ Jenkins infrastructure.

The plan is for you to run a `release-version` script from the CLI, which creates a release commit and pushes it to a tag, which Travis picks up and then builds and deploys for you. That way, you don't have to worry about doing that error-prone "double push to master" thing ever again. I may be able to get this working soon, since it fits in as part of our work to simplify the LOCI server infrastructure—one of my explicit eventual goals is to get rid of the ImageJ Jenkins.

**Comment by StephanPreibisch** [comment]
Hi @ctrueden, thanks a lot. Do you maybe have time for a quick Skype call today? I would like to release a new version of the old stitching and if you could just quickly guide me through, maybe everything becomes clear? Thanks so much for everything, Stephan

**Comment by ctrueden** [comment]
> Do you maybe have time for a quick Skype call today?

I could do a video chat on Friday after 0900 CT / 1600 CET. In the meantime, if you want to release Stitching today, I could simply cut the release for you using the `release-version.sh` script. Just let me know when the master branch is good to go, and I'll do it.

**Comment by StephanPreibisch** [comment]
Hi Curtis, tomorrow 16:00 is perfect, thanks! See you then

**Comment by imagejan** [comment]
I believe this is now fixed with https://github.com/scijava/pom-scijava/commit/4a4e5eff94f05a634ed2c2f48800d45e5a602933. Please re-open if there are remaining issues.
