### ISSUE TITLE
bigdataviewer-core-4.4.0 clashes with imglib2-5.1.0, should be 5.0.0

### ISSUE THREAD

**Issue by axtimwalde** [scijava/pom-scijava#62]

**Comment by ctrueden** [comment]
Why not a file a PR?

**Comment by axtimwalde** [comment]
Thanks @ctrueden.  Had only 5 minutes and noticed that it is clashing in the latest release that I know of 21.0.0. And wanted it to not fall by the wayside.

**Comment by ctrueden** [comment]
No worries @axtimwalde. Sorry the pom-scijava releases have not been 100% good since the ImgLib2 v5 transition. We are close now, though. I was waiting on releasing 22.0.0 until I had fully melted everything. It may be another week or two yet before I have time to finish testing, release it and upload all the updates to Fiji.
