### ISSUE TITLE
Update OMERO groupId from omero to org.openmicroscopy

### ISSUE THREAD

**Issue by imagejan** [scijava/pom-scijava#94]
Since version 5.5.0, the OMERO component artifacts changed their groupId from `omero` to `org.openmicroscopy`. See [this forum topic](https://forum.image.sc/t/release-of-omero-5-5-0/26600/7?u=imagejan). This will require a version bump of `pom-scijava` to the next major version.

See also https://github.com/imagej/imagej-omero/issues/106.

**Comment by ctrueden** [comment]
I started updating pom-scijava to use the new artifacts.

@joshmoore Are you planning to update pom-omero-client? It looks like it hasn't been updated for the artifact naming changes yet. I would love to scope import that POM into pom-scijava to inherit the OMERO version management with exclusions, instead of needing to work through all the exclusions again myself.

Or if no one else has worked through the latest exclusions yet: any chance of me contributing them to pom-omero-client for the community's greater benefit? Or you could ditch it in favor of extending pom-scijava directly. :wink: Even better would be to add the exclusions directly to the relevant components' dependency blocks, so people can just depend on them naively without running into the class clashes.

**Comment by ctrueden** [comment]
I finished working through the exclusions, including testing existing and removing obsolete ones. Here is the patch: 3e8ed5459bf190a67944942f8885ca837819a050. With that, I think this issue is resolved. I will update imagej-omero and imagej-omero-legacy to OMERO 5.5 after pom-scijava 28 is released.
